// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA26NkMNZINJhiWAecwitVO7vKQbWhBKJk',
    appId: '1:185041510818:ios:654d15c5e15461c08d52fb',
    messagingSenderId: '185041510818',
    projectId: 'frontier-finance-zambia',
    authDomain: 'frontier-finance-zambia.firebaseapp.com',
    storageBucket: 'frontier-finance-zambia.appspot.com',
    measurementId: 'G-YRVF1SMJGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaXvyHp1k-TwPFYJPxOK3E0txzdn-3FJQ',
    appId: '1:185041510818:web:db01be2007c26fea8d52fb',
    messagingSenderId: '185041510818',
    projectId: 'frontier-finance-zambia',
    storageBucket: 'frontier-finance-zambia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDahxVR_cFPb2gTKH2NY2wemA-RIR6Jnpw',
    appId: '1:185041510818:ios:654d15c5e15461c08d52fb',
    messagingSenderId: '185041510818',
    projectId: 'frontier-finance-zambia',
    storageBucket: 'frontier-finance-zambia.appspot.com',
    iosBundleId: 'com.example.finalTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDahxVR_cFPb2gTKH2NY2wemA-RIR6Jnpw',
    appId: '1:185041510818:ios:654d15c5e15461c08d52fb',
    messagingSenderId: '185041510818',
    projectId: 'frontier-finance-zambia',
    storageBucket: 'frontier-finance-zambia.appspot.com',
    iosBundleId: 'com.example.finalTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA26NkMNZINJhiWAecwitVO7vKQbWhBKJk',
    appId: '1:185041510818:ios:654d15c5e15461c08d52fb',
    messagingSenderId: '185041510818',
    projectId: 'frontier-finance-zambia',
    authDomain: 'frontier-finance-zambia.firebaseapp.com',
    storageBucket: 'frontier-finance-zambia.appspot.com',
    measurementId: 'G-YRVF1SMJGE',
  );
}
