// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCPazYNaFZT1IqWlfQhKCeSyDYmqiqlUs',
    appId: '1:717468538843:web:458dddeccfad517240b9fe',
    messagingSenderId: '717468538843',
    projectId: 'testing-5e7c1',
    authDomain: 'testing-5e7c1.firebaseapp.com',
    storageBucket: 'testing-5e7c1.appspot.com',
    measurementId: 'G-TN7RWVW152',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGz2pM2NRAMt2FsmUhY_3ggOgNzvYLFk',
    appId: '1:717468538843:android:eaa76fd7c8bc0bd340b9fe',
    messagingSenderId: '717468538843',
    projectId: 'testing-5e7c1',
    storageBucket: 'testing-5e7c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxeGzQuGjEoB3uBHiRfHpWBFEU-UiDGCs',
    appId: '1:717468538843:ios:f926b2035e2c557340b9fe',
    messagingSenderId: '717468538843',
    projectId: 'testing-5e7c1',
    storageBucket: 'testing-5e7c1.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxeGzQuGjEoB3uBHiRfHpWBFEU-UiDGCs',
    appId: '1:717468538843:ios:f926b2035e2c557340b9fe',
    messagingSenderId: '717468538843',
    projectId: 'testing-5e7c1',
    storageBucket: 'testing-5e7c1.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCPazYNaFZT1IqWlfQhKCeSyDYmqiqlUs',
    appId: '1:717468538843:web:1c27b8d753d139c840b9fe',
    messagingSenderId: '717468538843',
    projectId: 'testing-5e7c1',
    authDomain: 'testing-5e7c1.firebaseapp.com',
    storageBucket: 'testing-5e7c1.appspot.com',
    measurementId: 'G-37XQZDH4YF',
  );
}
